/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vistas;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author ktajt
 */
public class MenuVista extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuVista() {
        initComponents();
    }

    public void CargarPanelSecundario(javax.swing.JFrame pFrame, String pFrameNombre)
    {
        initComponents();
        panelSecundario.removeAll();
        panelSecundario.add(pFrame.getContentPane(), pFrameNombre);
        panelSecundario.revalidate();
        panelSecundario.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelPersonas = new javax.swing.JPanel();
        btnPersonas = new javax.swing.JLabel();
        panelBoletos = new javax.swing.JPanel();
        btnBoletos = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        btnInicio = new javax.swing.JLabel();
        panelSecundario = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(242, 88, 53));

        labelTitulo.setFont(new java.awt.Font("Fredoka One", 0, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Titulo");

        panelPersonas.setBackground(new java.awt.Color(242, 88, 53));
        panelPersonas.setForeground(new java.awt.Color(255, 255, 255));
        panelPersonas.setToolTipText("");

        btnPersonas.setBackground(new java.awt.Color(242, 88, 53));
        btnPersonas.setFont(new java.awt.Font("Fredoka One", 0, 18)); // NOI18N
        btnPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPersonas.setText("PERSONAS");
        btnPersonas.setFocusable(false);
        btnPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPersonasLayout = new javax.swing.GroupLayout(panelPersonas);
        panelPersonas.setLayout(panelPersonasLayout);
        panelPersonasLayout.setHorizontalGroup(
            panelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(panelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnPersonas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );
        panelPersonasLayout.setVerticalGroup(
            panelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(panelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        panelBoletos.setBackground(new java.awt.Color(242, 88, 53));
        panelBoletos.setForeground(new java.awt.Color(255, 255, 255));
        panelBoletos.setToolTipText("");

        btnBoletos.setBackground(new java.awt.Color(242, 88, 53));
        btnBoletos.setFont(new java.awt.Font("Fredoka One", 0, 18)); // NOI18N
        btnBoletos.setForeground(new java.awt.Color(255, 255, 255));
        btnBoletos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBoletos.setText("BOLETOS");
        btnBoletos.setFocusable(false);
        btnBoletos.setMaximumSize(new java.awt.Dimension(96, 23));
        btnBoletos.setMinimumSize(new java.awt.Dimension(96, 23));
        btnBoletos.setName(""); // NOI18N
        btnBoletos.setPreferredSize(new java.awt.Dimension(96, 23));
        btnBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBoletosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBoletosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBoletosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBoletosLayout = new javax.swing.GroupLayout(panelBoletos);
        panelBoletos.setLayout(panelBoletosLayout);
        panelBoletosLayout.setHorizontalGroup(
            panelBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(panelBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnBoletos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );
        panelBoletosLayout.setVerticalGroup(
            panelBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(panelBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        panelInicio.setBackground(new java.awt.Color(242, 88, 53));

        btnInicio.setBackground(new java.awt.Color(242, 88, 53));
        btnInicio.setFont(new java.awt.Font("Fredoka One", 1, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInicio.setText("INICIO");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(panelBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(318, 318, 318)
                    .addComponent(panelBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(438, Short.MAX_VALUE)))
        );

        panelBackground.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 800));

        panelSecundario.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelSecundarioLayout = new javax.swing.GroupLayout(panelSecundario);
        panelSecundario.setLayout(panelSecundarioLayout);
        panelSecundarioLayout.setHorizontalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        panelSecundarioLayout.setVerticalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        panelBackground.add(panelSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 830, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
        InicioVista inicioVista = new InicioVista();

        panelSecundario.removeAll();
        panelSecundario.add(inicioVista.getContentPane(), "Inicio");
        panelSecundario.revalidate();
        panelSecundario.repaint();
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:
        panelInicio.setBackground(new Color(217, 88, 51));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:
        panelInicio.setBackground(new Color(242, 88, 53));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonasMouseClicked
        // TODO add your handling code here:
        PersonaVista personaVista = new PersonaVista();
        panelSecundario.removeAll();
        panelSecundario.add(personaVista.getContentPane(), "Persona");
        panelSecundario.revalidate();
        panelSecundario.repaint();
    }//GEN-LAST:event_btnPersonasMouseClicked

    private void btnPersonasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonasMouseEntered
        // TODO add your handling code here:
        panelPersonas.setBackground(new Color(217, 88, 51));
    }//GEN-LAST:event_btnPersonasMouseEntered

    private void btnPersonasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonasMouseExited
        // TODO add your handling code here:
        panelPersonas.setBackground(new Color(242, 88, 53));
    }//GEN-LAST:event_btnPersonasMouseExited

    private void btnBoletosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoletosMouseClicked
        // TODO add your handling code here:
        BoletoVista boletoVista = new BoletoVista(this);
        panelSecundario.removeAll();
        panelSecundario.add(boletoVista.getContentPane(), "Boleto");
        panelSecundario.revalidate();
        panelSecundario.repaint();
    }//GEN-LAST:event_btnBoletosMouseClicked

    private void btnBoletosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoletosMouseEntered
        // TODO add your handling code here:
        panelBoletos.setBackground(new Color(217, 88, 51));
    }//GEN-LAST:event_btnBoletosMouseEntered

    private void btnBoletosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoletosMouseExited
        // TODO add your handling code here:
        panelBoletos.setBackground(new Color(242, 88, 53));
    }//GEN-LAST:event_btnBoletosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBoletos;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JLabel btnPersonas;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBoletos;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPersonas;
    protected javax.swing.JPanel panelSecundario;
    // End of variables declaration//GEN-END:variables
}
